Fix python 3.8 failures
openedx-unsupported/edx-analytics-dashboard pull request #1019
Opened 2020-05-13 13:03 UTC by iamsobanjaved

add xenial dist in travis.yml for python 3.8

JIRA: [BOM-1627](https://openedx.atlassian.net/browse/BOM-1627)

2020-05-28 11:25 UTC, mzulqarnain1 requested changes

2020-05-28 11:25 UTC, mzulqarnain1 commented on .travis.yml
> +      sudo apt-get install python3.8 python3.8-distutils python3.8-dev -y;"
This is not needed anymore IMO, we are already installing Python 3.8 in our docker images now.

2020-05-28 11:48 UTC, iamsobanjaved commented on .travis.yml
> +      sudo apt-get install python3.8 python3.8-distutils python3.8-dev -y;"
Will it work now if i remove this thing?

2020-05-28 11:51 UTC, mzulqarnain1 commented on .travis.yml
> +      sudo apt-get install python3.8 python3.8-distutils python3.8-dev -y;"
It should work now.

2020-05-29 04:59 UTC, iamsobanjaved commented on .travis.yml
> +      sudo apt-get install python3.8 python3.8-distutils python3.8-dev -y;"
Removed

2020-05-29 06:10 UTC, mraarif approved these changes

2020-05-29 09:16 UTC, mzulqarnain1 approved these changes

2020-06-04 12:19 UTC, iamsobanjaved commented
@morenol kindly review it

2020-06-04 14:22 UTC, morenol approved these changes

2020-06-09 14:59 UTC, merged