feat: Added upgrade-python-requirements workflow
openedx-unsupported/edx-analytics-dashboard pull request #1135
Opened 2021-06-17 12:29 UTC by Jawayria

JIRA: https://openedx.atlassian.net/browse/BOM-2600

2021-06-17 19:01 UTC, mraarif approved these changes

2021-07-14 15:03 UTC, Jawayria commented
@edx/masters-devs-cosmonauts as this repository is owned by your team, you need to get access for this repo so that your team could get tagged on **Upgrade requirements prs** generated by this new GitHub workflow. 
Please review this PR as well.

2021-07-15 17:31 UTC, matthugs commented
Added the @edx/masters-devs-cosmonauts team with Write permissions on this repo, such that the pings will work.

2021-07-15 17:33 UTC, matthugs requested changes
Could you apply the same feedback as I gave to https://github.com/edx/portal-designer/pull/135/files ? Although we never moved the jenkins-initiated upgrades over to alert us instead of Data Engineering, it'd be great to have this following the same pattern as all our other repos.

2021-10-20 15:15 UTC, Jawayria commented
@matthugs @edx/edx-data-engineering please review

2021-10-20 15:31 UTC, matthugs approved these changes

2021-10-20 15:31 UTC, matthugs commented on .github/workflows/upgrade-python-requirements.yml
> +    - cron: "15 3 15,30 * *"
```suggestion
    - cron: "15 3 15,29 * *"
```
```suggestion
    # will start the job at 3:15 UTC on 15th and 29th of every month
    - cron: "15 3 15,29 * *"
```

2021-10-21 12:32 UTC, merged