fix: remove node_modules strings from extract_translations
openedx-unsupported/edx-analytics-dashboard pull request #1213
Opened 2021-11-02 17:44 UTC by IDerr

Remove node modules strings from en translations as not part of the edX Project

2021-11-02 17:44 UTC, edx-webhook commented
Thanks for the pull request, @IDerr! I've created [OSPR-6201](https://openedx.atlassian.net/browse/OSPR-6201) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-11-02 17:46 UTC, IDerr commented
@natabene I've opened this PR, seems a better way to fix this issue, now that I've understood better how translations are extracted :)

Thanks

2021-11-04 16:12 UTC, IDerr commented
Thanks for the CI build, the error is normal, because the PR changes translations files

Is there any way to bypass the CI failure, or getting reviewed manually ? 

Best regards,
IDerr

2021-11-04 16:24 UTC, natabene commented
@IDerr Thank you for your contribution. I am not sure about the CI part, let's see what the owning squad thinks.

2021-11-04 19:35 UTC, IDerr commented
Ok thank you !

2021-11-09 20:12 UTC, IDerr commented
Any news about this @natabene ?

2021-11-12 03:18 UTC, natabene commented
@IDerr Not yet.

2021-11-12 14:25 UTC, schenedx reviewed
@IDerr I am a member of the edx-analytics-dashboard owning team. Thank you for the PR.
While you are technically correct that the strings within the node_moduls are not part of the edx code. The strings within those library might surface to the users through UI. In this case, that chance is super small, therefore I intend to accept this change. That said, could you talk about why these strings should not be translated? Do these present any difficult on translations in your openedX environment?

As for getting the CI pass, you would need to check in the po file changes generated by this PR. The way to achieve that is to do `make generate_fake_translations` in your machine. See https://github.com/edx/edx-analytics-dashboard/blob/master/Makefile#L153.

Feel free to pin me directly on this PR with your response.

2021-11-12 14:27 UTC, schenedx requested changes
Requesting for 2 things: 

1. Check in the changed `.po` file
2. Provide an explanantion why this change is valuable to you.

2022-01-12 03:08 UTC, natabene commented
@IDerr Just checking if you are still interested in pursuing this PR. Have you had a chance to look into request by @schenedx ?

2022-01-18 22:49 UTC, IDerr commented
Hi @natabene, I will not pursue, don't have enough time to continue this, I'll just leave strings as untranslated in the french version in Transifex atm.

Thanks a lot for your help.

2022-01-18 22:49 UTC, closed without merging

2022-01-18 22:49 UTC, edx-webhook commented
@IDerr Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-analytics-dashboard&entry.867055334=https://github.com/openedx/edx-analytics-dashboard/pull/1213&entry.1484655318=https://github.com/IDerr&entry.752974735=2021-11-02+17:44&entry.1917517419=2022-01-18+22:49&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->