AN-6185 Skip link
openedx-unsupported/edx-analytics-dashboard pull request #573
Opened 2016-10-24 21:42 UTC by thallada

For the sake of accessibility, I think we should merge these changes. Unfortunately, I was never able to get the a11y test that checks for the skip link to work, so it is left ignored in the a11y test config.

![Skip link screenshot](https://drive.google.com/uc?export=download&id=0B_ZVhDsMa557T0xFNHMwTTA2c1U)

2016-10-25 15:17 UTC, dsjen approved these changes
I left two suggestions--take them or leave them!  We should probably get an a11y review too.

2016-10-25 15:17 UTC, dsjen commented on analytics_dashboard/static/sass/_base.scss
> +.skip-link:active,
This might be a tad cleaner if embedded within the `.skip-link` selector as:

```
.skip-link {
    &:focus,
    &:hover {
        ...
    }
    ...
```

2016-10-25 15:17 UTC, dsjen commented on analytics_dashboard/templates/header.html
> +<a href="#content" class="skip-link">{% trans 'Skip to content' %}</a>
This idea is very much possibly overkill, but you could create a skip-link partial that's included.  I think the benefit would be consistency in how a skip link is created and centralized wording definition.  Maybe a bit much though for a single line!

2016-10-25 16:42 UTC, thallada commented on analytics_dashboard/templates/header.html
> +<a href="#content" class="skip-link">{% trans 'Skip to content' %}</a>
That makes sense. It should make it easier if we ever make a completely new page as well.

2016-10-25 16:42 UTC, thallada commented on analytics_dashboard/static/sass/_base.scss
> +.skip-link:active,
Will do

2016-10-25 17:29 UTC, thallada commented
@edx/edx-accessibility can you review this? This PR adds a skip link to Insights.

2016-10-27 19:49 UTC, cptvitamin requested changes

2016-10-27 19:49 UTC, cptvitamin commented on analytics_dashboard/core/templates/core/landing.html
> +            <div class="grid-container grid-manual landing" id="content">
@thallada can we make this a ```<main>``` element instead of just a div? It's more semantic and will benefit SR users (and browsers and search engines, and all machines!) Also, in order to address a well known bug in Safari, we have to add an attribute of ```tabindex="1"``` here.  This may have the unwanted side effect of a visible border around the entire main content region whenever the skip to main content link is used, or whenver anyone clicks in that region!  You may need to add some CSS that specifies ```outline:none;``` on the main element.  One more thing. I like to add an ```aria-label="Content"``` to the main element so that when it is listed in a list of available regions, it clearly identifies itself as "Main Content"

2016-10-27 19:49 UTC, cptvitamin commented on analytics_dashboard/core/templates/core/landing.html
>              <header class="navbar navbar-default" role="banner" aria-label="main" id="nav">
```role=banner``` is not necessary here.  Let's remove it while we're in here.  I also don't think the ```aria-label``` is doing this element any justice either, so let's get rid of that as well.  I see it has an ```id="nav"``` .  Does this region contain nav elements?  if so, we may want to isolate those and wrap them in a ```<nav>``` element if they aren't already and make sure that element has an ```aria-label``` that describes the purpose of the navigation, like Main, or Site etc.

2016-10-27 20:15 UTC, thallada commented on analytics_dashboard/core/templates/core/landing.html
>              <header class="navbar navbar-default" role="banner" aria-label="main" id="nav">
Will do!

About the id="nav"... this is really confusing, but this header isn't really the main nav. It wraps the edx logo, the title of the current course, the help link, and the username/logout dropdown.

Below it is the black navbar that has navigation links like "Course Home", "Engagement", "Enrollment", etc. That element is a `<nav>`.

Do you have any suggestions for what to do with multiple levels of different navbars? Should this one still be a `<nav>`?

2016-10-31 15:53 UTC, thallada commented
@cptvitamin I addressed all of you comments except for the point about the `<nav>` element (see my comment above). That block is a `<header>`. The real nav is below it and wrapped in a `<nav>` element.

Let me know what you think. And, if it looks good, can you approve? Thanks!

2016-11-01 19:34 UTC, cptvitamin requested changes

2016-11-01 19:34 UTC, cptvitamin commented on analytics_dashboard/core/templates/core/landing.html
> +            <main class="grid-container grid-manual landing" id="content" tabindex="1" aria-label="{% trans Content %}">
@thallada very important that this is a negative one (-1) not a 1.   tabindex should never be a positive integer.  Only useful values are zero and -1

2016-11-07 20:39 UTC, thallada commented
@cptvitamin I addressed the tabindex issue you pointed out. Do you see any other issues?

2016-11-07 21:40 UTC, cptvitamin commented
@thallada this looks great.  👍  Do you have any method for ensuring that the target exists on every page the skip link appears on?  We had to do this for edx-platform to ensure that there indeed was an element with a matching ID on every page.

2016-11-10 15:43 UTC, cptvitamin approved these changes

2016-11-14 17:52 UTC, thallada commented
I added an acceptance test that tests that every page has a skip link, that it points to a valid element, and that tab enter will navigate to it.

2016-11-14 17:53 UTC, merged