Update documentation for Courses page to reflect enrollment cards
openedx-unsupported/edx-analytics-dashboard pull request #654
Opened 2017-03-24 17:18 UTC by srpearce

## [DOC-3604](https://openedx.atlassian.net/browse/DOC-3604)

This PR updates information about the Courses page to reflect the four cards that show enrollment metrics. It also includes minor updates to correct outdated information.

### Date Needed (optional)

ASAP (feature released 3/22)

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Engineering review: @dsjen or @thallada 
- [ ] Doc team review (copy edit): @edx/doc
- [ ] Product review: @katymyw 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-03-24 17:49 UTC, grantgoodmanedX approved these changes
Looks good. I made one highly optional suggestion. +1

2017-03-24 17:49 UTC, grantgoodmanedX commented on docs/en_us/dashboard/source/Courses_Page.rst
> +by either the “Total Enrollment” or “Current Enrollment” columns, depending on
"depending on which metric you are interested in."

2017-03-24 18:07 UTC, thallada requested changes
I left a couple of suggestions inline.

2017-03-24 18:07 UTC, thallada commented on docs/en_us/dashboard/source/Courses_Page.rst
> +automatically.
Maybe it would be useful to mention here that you can also get to the Courses page from anywhere else in insights be clicking the "edX Insights" logo in the top left corner.

Edit: oh, I see you mention that in the section below. I think it would be useful to mention it here too.

2017-03-24 18:07 UTC, thallada commented on docs/en_us/dashboard/source/Courses_Page.rst
> +  verified enrollment track.
I think "course" should be plural in these descriptions.

2017-03-24 18:07 UTC, thallada commented on docs/en_us/dashboard/source/Courses_Page.rst
> +Access Data for a Specific Course
nit: I feel like a better heading for this content would be "Locate a Specific Course".

2017-03-27 01:48 UTC, katymyw commented on docs/en_us/dashboard/source/Courses_Page.rst
> +  verified enrollment track.
I want to flag a potentially confusing thing here, and see what you think. When we refer to number of or increase/decrease in 'learners' that may imply unique learners across all courses. The metric being aggregated here is actually enrollments, so, e.g., if a learner is enrolled in 2 courses, they would count as 2 here. In other places (e.g., the tooltips and other pages) I think we typically just refer to 'enrollments' to avoid this issue. 

Curious what you think, though. I do prefer the word 'learner' if it is clear.

2017-03-28 17:22 UTC, srpearce commented on docs/en_us/dashboard/source/Courses_Page.rst
> +Access Data for a Specific Course
Thanks for the suggestion. I was thinking more of what the users' ultimate goal here is—the reason they want to locate a course is so that they can access course data. I was thinking that might be more searchable as well.

2017-03-28 17:22 UTC, srpearce commented on docs/en_us/dashboard/source/Courses_Page.rst
> +  verified enrollment track.
I've made some changes—let me know what you think.

2017-03-28 17:22 UTC, srpearce commented on docs/en_us/dashboard/source/Courses_Page.rst
> +automatically.
Excellent suggestion. :-)

2017-03-29 18:02 UTC, thallada commented on docs/en_us/dashboard/source/Courses_Page.rst
> +  courses. all of your courses.
This looks like a typo?

2017-04-03 21:05 UTC, merged